<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Your game folder -->
    <MuseDashPath>C:\Steam\SteamLibrary\steamapps\common\Muse Dash</MuseDashPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(MuseDashPath)\MelonLoader\net6\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppAssembly-CSharp">
      <HintPath>$(MuseDashPath)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppcom.rlabrecque.steamworks.net">
      <HintPath>$(MuseDashPath)\MelonLoader\Il2CppAssemblies\Il2Cppcom.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(MuseDashPath)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(MuseDashPath)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MuseDashPath)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>$(MuseDashPath)\MelonLoader\net6\MelonLoader.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
